// <auto-generated />
using System;
using FinancePlanning.Infrastructure;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace FinancePlanning.Infrastructure.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("FinancePlanning.Infrastructure.Account", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("BankCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.HasIndex("BankCode");

                    b.ToTable("Accounts");
                });

            modelBuilder.Entity("FinancePlanning.Infrastructure.Bank", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("Banks");

                    b.HasData(
                        new
                        {
                            Code = "BCS",
                            Name = "БКС"
                        },
                        new
                        {
                            Code = "T",
                            Name = "T"
                        },
                        new
                        {
                            Code = "CSH",
                            Name = "Наличные"
                        },
                        new
                        {
                            Code = "Ya",
                            Name = "Яндекс"
                        },
                        new
                        {
                            Code = "Oz",
                            Name = "Озон"
                        });
                });

            modelBuilder.Entity("FinancePlanning.Infrastructure.Distribution", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<int>("IncomeId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AccountCode");

                    b.HasIndex("IncomeId");

                    b.ToTable("Distributions");
                });

            modelBuilder.Entity("FinancePlanning.Infrastructure.Income", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("IncomeSourceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("IncomeSourceCode");

                    b.ToTable("Incomes");
                });

            modelBuilder.Entity("FinancePlanning.Infrastructure.IncomeSource", b =>
                {
                    b.Property<string>("Code")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PersonName")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Code");

                    b.ToTable("IncomeSources");
                });

            modelBuilder.Entity("FinancePlanning.Infrastructure.Rule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AccountCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric");

                    b.Property<string>("IncomeSourceCode")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AccountCode");

                    b.HasIndex("IncomeSourceCode");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FinancePlanning.Infrastructure.Account", b =>
                {
                    b.HasOne("FinancePlanning.Infrastructure.Bank", "Bank")
                        .WithMany("Accounts")
                        .HasForeignKey("BankCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bank");
                });

            modelBuilder.Entity("FinancePlanning.Infrastructure.Distribution", b =>
                {
                    b.HasOne("FinancePlanning.Infrastructure.Account", "Account")
                        .WithMany("Distributions")
                        .HasForeignKey("AccountCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancePlanning.Infrastructure.Income", "Income")
                        .WithMany("Distributions")
                        .HasForeignKey("IncomeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("Income");
                });

            modelBuilder.Entity("FinancePlanning.Infrastructure.Income", b =>
                {
                    b.HasOne("FinancePlanning.Infrastructure.IncomeSource", "IncomeSource")
                        .WithMany("Incomes")
                        .HasForeignKey("IncomeSourceCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IncomeSource");
                });

            modelBuilder.Entity("FinancePlanning.Infrastructure.Rule", b =>
                {
                    b.HasOne("FinancePlanning.Infrastructure.Account", "Account")
                        .WithMany("Rules")
                        .HasForeignKey("AccountCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinancePlanning.Infrastructure.IncomeSource", "IncomeSource")
                        .WithMany("Rules")
                        .HasForeignKey("IncomeSourceCode")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("IncomeSource");
                });

            modelBuilder.Entity("FinancePlanning.Infrastructure.Account", b =>
                {
                    b.Navigation("Distributions");

                    b.Navigation("Rules");
                });

            modelBuilder.Entity("FinancePlanning.Infrastructure.Bank", b =>
                {
                    b.Navigation("Accounts");
                });

            modelBuilder.Entity("FinancePlanning.Infrastructure.Income", b =>
                {
                    b.Navigation("Distributions");
                });

            modelBuilder.Entity("FinancePlanning.Infrastructure.IncomeSource", b =>
                {
                    b.Navigation("Incomes");

                    b.Navigation("Rules");
                });
#pragma warning restore 612, 618
        }
    }
}
